// File generated by `flutterfire` CLI.
// This file should be auto-generated or manually created by running:
// `flutterfire configure` with your Firebase project
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWebPlatform',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'accounting-app',
    authDomain: 'accounting-app.firebaseapp.com',
    databaseURL: 'https://accounting-app.firebaseio.com',
    storageBucket: 'accounting-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForAndroid',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'accounting-app',
    databaseURL: 'https://accounting-app.firebaseio.com',
    storageBucket: 'accounting-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForIOS',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'accounting-app',
    databaseURL: 'https://accounting-app.firebaseio.com',
    storageBucket: 'accounting-app.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForMacOS',
    appId: '1:000000000000:macos:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'accounting-app',
    databaseURL: 'https://accounting-app.firebaseio.com',
    storageBucket: 'accounting-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWindows',
    appId: '1:000000000000:windows:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'accounting-app',
    databaseURL: 'https://accounting-app.firebaseio.com',
    storageBucket: 'accounting-app.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForLinux',
    appId: '1:000000000000:linux:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'accounting-app',
    databaseURL: 'https://accounting-app.firebaseio.com',
    storageBucket: 'accounting-app.appspot.com',
  );
}
